[kernel_offsets]
init_task_off = 0x09bcb580
init_uts_ns_off = 0x09bcb328
selinux_enforcing_off = 0x09db7018
security_hook_heads_off = 0x094dd818
kmalloc_caches_off = 0x09ac1298
selinux_blob_sizes_off = 0x0
