kimage_text_base = 0xffffff8008080000

# file_operations / function pointers
random_misc_fops_off = 0x4000fa0200
ashmem_misc_fops_off = 0x01c3ca18
ashmem_fops_off = 0x01078230
ashmem_ioctl_off = 0x009eb1c0
ashmem_compat_ioctl_off = 0x009eb78c
ashmem_mmap_off = 0x009eb7d8
ashmem_open_off = 0x009eb944
ashmem_release_off = 0x009eb9c4
ashmem_show_fdinfo_off = 0x009ebad8
ashmem_read_iter_off = 0x009eb10c
configfs_read_file_off = 0x002dc67c
configfs_write_bin_file_off = 0x002dcb38
copy_splice_read_off = 0x0026fe80
noop_llseek_off = 0x0022fa84

# kernel variables
init_task_off = 0x01b4b580
init_uts_ns_off = 0x01b4b328
empty_zero_page_off = 0x01cf7000
root_task_group_off = 0x01cfdd80
selinux_blob_sizes_off = 0x0
selinux_enforcing_off = 0x01d36ff8
security_hook_heads_off = 0x0145d818
kmalloc_caches_off = 0x0145d318
anon_pipe_buf_ops_off = 0x00fd2980

# slide (boot_id infoleak) variables
slide_random_boot_id_data_off = 0x01bda5e8
slide_sysctl_bootid_off = 0x01d4c849
slide_loggers_0_1_off = 0x01b41988
slide_nfulnl_logger_off = 0x01b41a58
